# Generated by Django 5.2.5 on 2025-11-09 14:26

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='posts/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'], message='MP4,MOV,AVIから動画を選択してください'), posts.models.validate_video_duration]),
        ),
    ]
