# Generated by Django 5.2.5 on 2026-01-16 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_posts', through='posts.SavePost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
