# Generated by Django 5.2.5 on 2026-01-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_saved_users_alter_savepost_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='helped_users',
            field=models.ManyToManyField(related_name='helped_posts', through='posts.HelpPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
