# Generated by Django 5.2.5 on 2026-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_commentreply_supplementreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
