# Generated by Django 5.2.5 on 2026-01-06 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/profile_images/default_profile.png', null=True, upload_to='accounts/profile_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], message='JPEGまたはPNG画像を選択してください')]),
        ),
    ]
