# Generated by Django 5.2.5 on 2026-04-12 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], message='JPEGまたはPNG画像を選択してください')]),
        ),
    ]
