# Generated by Django 5.2.5 on 2026-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'コメント'), ('comment_reply', 'コメントへの返信'), ('supplement', '補足説明'), ('supplement_reply', '補足説明への返信'), ('help', '役立った'), ('save', '保存')], max_length=30),
        ),
    ]
